import { IAgeRange } from './mindmap-interface';

export interface IHealthData {
  id?: string;
  index?: number;
  text: string;
  perform_physical_exam?: string;
  display?: string;
  isRequired?: boolean;
  multi_choice?: boolean;
  exclude_from_multi_choice?: boolean;
  having_nested_question?:boolean;
  compare_duplicate_node?: string;
  enable_exclusive_option?:boolean;
  is_exclusive_option?:boolean;
  display_or?: string;
  display_hi?: string;
  display_mr?: string;
  pop_up?: string;
  pop_up_hi?: string;
  pop_up_or?: string;
  pop_up_mr?: string;
  language?: string;
  input_type?: string;
  gender?: string;
  age_min?: IAgeRange;
  age_max?: IAgeRange;
  range_min?: number;
  range_max?: number;
  pos_condition?: string;
  neg_condition?: string;
  citation?: string;
  snomed?: string;
  icd_11?: string;
  loinc?: string;
  job_aid_type?: string;
  job_aid_file?: string;
  associated_complaint?: string;
  options?: Array<IHealthData>;
}
