const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envFile = path.join(root, '.env');
const envDir = path.join(root, 'src', 'environments');

function readEnv() {
  const values = {};
  if (!fs.existsSync(envFile)) return values;
  for (const line of fs.readFileSync(envFile, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

const env = { ...readEnv(), ...process.env };
const apiKey = env.OPENAI_API_KEY || '';
const model = env.OPENAI_MODEL || 'gpt-5.5';

function write(fileName, production) {
  const contents =
    '// Generated by scripts/set-env.js. Do not edit and do not commit.\n' +
    'export const environment = {\n' +
    `  production: ${production},\n` +
    `  openaiApiKey: ${JSON.stringify(apiKey)},\n` +
    `  openaiModel: ${JSON.stringify(model)},\n` +
    '};\n';
  fs.writeFileSync(path.join(envDir, fileName), contents);
}

write('environment.ts', false);
write('environment.prod.ts', true);

const source = fs.existsSync(envFile) ? '.env' : 'process environment';
console.log(
  apiKey
    ? `set-env: wrote environments with an OpenAI key from ${source} (model ${model}).`
    : 'set-env: no OPENAI_API_KEY found. The Suggest button will be hidden.'
);
